name: AutoAnalysisCommit

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pytz
          pip install matplotlib
          pip install numpy
          
      - name: Run main.py
        run: |
          python main.py
      
      - name: Run a multi-line script
        run: |
          git config user.name "Broccolingual"
          git config user.email "63525348+broccolingual@users.noreply.github.com"
          git add .
          git commit -m "update: Analysis Data Update | ${{ steps.date.outputs.date }}"
          git pull
          git push origin master
