# This is a basic workflow to help you get started with Actions

name: AutoAnalysisCommit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pytz
          pip install matplotlib
          pip install numpy
          
      - name: Run main.py
        run: |
          python main.py
      
      - name: Run a multi-line script
        run: |
          git config user.name "Broccolingual"
          git config user.email "63525348+broccolingual@users.noreply.github.com"
          git add .
          git commit -m "update: Analysis Data Update"
          git pull
          git push origin master
